src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Client", inversedBy="user", cascade={"persist", "remove"})
     */
    private $client;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Owner", inversedBy="user", cascade={"persist", "remove"})
     */
    private $Owner;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): self
    {
        $this->client = $client;

        return $this;
    }

    public function getOwner(): ?Owner
    {
        return $this->Owner;
    }

    public function setOwner(?Owner $Owner): self
    {
        $this->Owner = $Owner;

        return $this;
    }

    public function addRole($role):self
    {
        if(!in_array($role,$this->roles)) {
            $this->roles[] = $role;
        }
        return $this;
    }

}

src/Controller/ProfileController.php
<?php

namespace App\Controller;

use App\Entity\User;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/profile")
 */
class ProfileController extends AbstractController
{

    /**
     * @Route("/mine", name="my_profile")
     */
    public function myProfile() {
        return $this->redirectToRoute("profile", array("user" => $this->getUser()->getId()));
    }

    /**
     * @Route("/{user}", requirements={"user": "\d+"}, name="profile")
     */
    public function show(User $user)
    {

        return $this->render('profile/show.html.twig', [
            'user' => $user,
        ]);
    }
}

templates/profile/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profil de {{ user.email }}{% endblock %}

{% block body %}
    <div class="container">
        <h1 class="display-4">Profil de {{ user.email }}</h1><span class="small">(oui dans la vraie vie on met pas l'adresse e-mail comme ça)</span>
        {% if user.owner is not null %}
            <div>
                <h2>Informations de prioritaire</h2>
                {{ user.owner }}

                <div>
                    Contact:
                    <ul>
                        <li>
                            Adresse postale: {{ user.owner.address }}
                        </li>
                        <li>
                            <a href="mailto:{{ user.email }}">{{ user.email }}</a>
                        </li>
                    </ul>

                </div>

            </div>
        {% endif %}

        {% if user.client is not null %}
            <div>
                <h2>Informations de client</h2>
                {{ user.email }}

                Bah on a pas grand chose en plus...
            </div>
        {% endif %}
    </div>
{% endblock %}